### ISSUE TITLE
Install Moodle

### ISSUE THREAD

**Issue by Miguel2807** [ISCOUTB/AS-Savio-2025#1]

**Comment by Miguel2807** [comment]
INSTALACIÓN DE MOODLE UTILIZANDO DOCKER

Moodle es un sistema de gestión de aprendizaje de código abierto utilizado para crear y gestionar cursos en línea. Se procederá a describir el proceso de instalación de Moodle utilizando Docker, una herramienta de virtualización que permite desplegar aplicaciones mediante contenedores.


 Creación del Entorno de Moodle
Para instalar Moodle en Docker, se deben seguir los siguientes pasos:

1. Creación de un Directorio para Moodle
Se crea una carpeta en la cual se almacenará la configuración de Docker:
En powershell (Windows) se ejecutan los siguientes comandos
mkdir moodle
cd moodle

2. Creación del Archivo de Configuración
Dentro de la carpeta creada, se genera un archivo `docker-compose.yml` con la configuración necesaria para descargar Moodle 

New-Item -Path . -Name "docker-compose.yml" -ItemType "file"
notepad docker-compose.yml


Se agrega el siguiente contenido al archivo:
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: alpyroot
      MYSQL_DATABASE: alpydb
      MYSQL_USER: alpyuser
      MYSQL_PASSWORD: alpypass
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    container_name: apache_php
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

3. Ejecución del Contenedor
Para iniciar Moodle y la base de datos, se ejecuta el siguiente comando en PowerShell o la terminal dentro de la carpeta moodle:

docker-compose up -d

Este comando descarga las imágenes de Moodle y la base de datos si no están disponibles localmente y levanta los contenedores en segundo plano.




Una vez que los contenedores están en funcionamiento, se puede acceder a Moodle desde un navegador web ingresando la siguiente dirección:

http://localhost:8080

![Image](https://github.com/user-attachments/assets/eec943b4-7afe-4c3e-9915-ee57f4948a14)

**Comment by Johan-G27** [comment]
Para instalar Moodle en Docker, primeramente se creó una carpeta(Moodle) donde están contenidos los archivos Dockerfile,  docker-compose.yml y custom.ini. Necesarios para poder crear los contenedores con el comando  (docker-compose up -d)

Luego fue necesario ingresar al contenedor de apache_php y modificar su archivo .conf para cambiar los permisos. Posterior a ello se descargó Moodle en el contenedor.

![Image](https://github.com/user-attachments/assets/88e66dcb-8d54-4508-8555-70c68d4aa46f)

**Comment by Jorgeivan6** [comment]
#### **los pasos realizados para la instalación**

1. **Creamos el entorno de Moodle**  
   Abre PowerShell en Windows y ejecuta:
   ```powershell
   mkdir moodle
   cd moodle
   ```

2. **Despues creamos el archivo de configuración**  
   Dentro de la carpeta, crea un archivo `docker-compose.yml` con el siguiente contenido:

   ```powershell
   New-Item -Path . -Name "docker-compose.yml" -ItemType "file"
   notepad docker-compose.yml
   ```

   Luego, se copia y pega la siguiente configuración en el archivo:

   ```yaml
   services:
     db:
       image: mysql:8.0
       container_name: mysql
       restart: always
       ports:
         - 3306:3306
       environment:
         MYSQL_ROOT_PASSWORD: alpyroot
         MYSQL_DATABASE: alpydb
         MYSQL_USER: alpyuser
         MYSQL_PASSWORD: alpypass
       volumes:
         - ./mysql_data:/var/lib/mysql
       networks:
         - app-network

     web:
       build: .
       container_name: apache_php
       restart: always
       ports:
         - "80:80"
       volumes:
         - ./moodle:/var/www/html
         - ./moodledata:/var/www/moodledata
       depends_on:
         - db
       networks:
         - app-network

   networks:
     app-network:
       driver: bridge
   ```

3. **Ejecutar los contenedores**  
   Inicia Moodle y la base de datos con:
   ```powershell
   docker-compose up -d
   ```

   Este comando descargará las imágenes necesarias y ejecutará los contenedores en segundo plano.

4. **Acceder a Moodle**  
   Una vez que los contenedores estén en funcionamiento, abre un navegador y ve a:

   ```
   http://localhost:8080
   ```

También se presentaron varios errores de los cuales se solucionaron con varios comandos, y buscando información en internet.


![Image](https://github.com/user-attachments/assets/2c89159e-d2a7-454a-8864-13b961a0a7f3)
